import { Injectable } from '@angular/core';
import { HttpService } from '../../shared/http/http.service';

@Injectable()
export class MainBusinessService {

  constructor(private httpService: HttpService) { }

  api: any = {
  }

  menuData() {
    let menuData = [
      {
        "id": "28",
        "parentId": "20",
        "name": "菜单管理",
        "keyWord": "cdgl",
        "icon": "fa-tree",
        "children": [{
          "id": "29",
          "parentId": "28",
          "name": "菜单管理",
          "keyWord": "cdtj",
          "icon": "fa-plus-circle",
          "url": "/app/menu/menuList"
        }]
      }, {
        "id": "123",
        "parentId": "20",
        "name": "部门管理",
        "keyWord": "cdgl",
        "icon": "fa-th",
        "children": [{
          "id": "124",
          "parentId": "123",
          "name": "部门编辑",
          "keyWord": "bmbj",
          "icon": 'fa-th-large',
          "url": '/app/department/departmentList'
        }, {
          "id": "125",
          "parentId": "123",
          "name": "岗位权限",
          "keyWord": "gwqx",
          "icon": 'fa-thumbs-up',
          "url": '/app/department/powerList'
        }]
      }, {
        "id": "20",
        "parentId": "0",
        "name": "用户角色",
        "keyWord": "qxgl",
        "icon": 'fa-user',
        "isExpend": false,
        "children": [{
          "id": "23",
          "parentId": "20",
          "name": "用户列表",
          "keyWord": "yhlb",
          "icon": "fa-list-alt",
          "url": "/app/user/userList"
        }]
      },
      {
        "id": "131",
        "parentId": "132",
        "name": "节目单管理",
        "keyWord": "jmd",
        "icon": "fa-paw",
        "children": [{
          "id": "134",
          "parentId": "131",
          "name": "节目单",
          "keyWord": "jmd",
          "icon": 'fa-tree',
          "url": '/app/program/programList'
        }]
      }, {
        "id": "141",
        "parentId": "142",
        "name": "页面管理",
        "keyWord": "ymgl",
        "icon": "fa-leanpub",
        "children": [{
          "id": "144",
          "parentId": "141",
          "name": "运营元素管理",
          "keyWord": "yyysgl",
          "icon": 'fa-server',
          "url": '/app/page/elementList'
        }, {
          "id": "145",
          "parentId": "141",
          "name": "页面管理",
          "keyWord": "yygm",
          "icon": 'fa-clipboard',
          "url": '/app/page/pageList'
        }, {
          "id": "146",
          "parentId": "141",
          "name": "产品-页面关联管理",
          "keyWord": "yyysgl",
          "icon": 'fa-shekel',
          "url": '/app/page/productList'
        }]
      }, {
        "id": "151",
        "parentId": "152",
        "name": "订购管理",
        "keyWord": "dggl",
        "icon": "fa-shopping-cart",
        "children": [{
          "id": "154",
          "parentId": "151",
          "name": "订购规则",
          "keyWord": "dggz",
          "icon": 'fa-server',
          "url": '/app/order/ruleList'
        }, {
          "id": "155",
          "parentId": "151",
          "name": "基础数据管理",
          "keyWord": "jjsj",
          "icon": 'fa-database',
          "children": [{
            "id": "156",
            "parentId": "155",
            "name": "产品管理",
            "keyWord": "cpgl",
            "icon": 'fa-server',
            "url": '/app/order/productList'
          }, {
            "id": "157",
            "parentId": "155",
            "name": "规则关联管理",
            "keyWord": "gzglgl",
            "icon": 'fa-server',
            "url": '/app/order/rurelateList'
          }, {
            "id": "158",
            "parentId": "155",
            "name": "关联管理",
            "keyWord": "glgl",
            "icon": 'fa-server',
            "url": '/app/order/relateList'
          }]
        }]
      }, {
        "id": "161",
        "parentId": "162",
        "name": "入口管理",
        "keyWord": "rkgl",
        "icon": "fa-window-restore",
        "children": [{
          "id": "164",
          "parentId": "161",
          "name": "访问入口",
          "keyWord": "fwrk",
          "icon": 'fa-window-maximize',
          "url": '/app/entry/visitList'
        }, {
          "id": "165",
          "parentId": "161",
          "name": "基础数据管理",
          "keyWord": "jjsj",
          "icon": 'fa-database',
          "children": [{
            "id": "166",
            "parentId": "165",
            "name": "对象-版本管理",
            "keyWord": "dxbb",
            "icon": 'fa-server',
            "url": '/app/entry/objverList'
          }, {
            "id": "167",
            "parentId": "165",
            "name": "项目-对象管理",
            "keyWord": "xmdx",
            "icon": 'fa-server',
            "url": '/app/entry/projectList'
          }, {
            "id": "168",
            "parentId": "165",
            "name": "关联管理",
            "keyWord": "glgl",
            "icon": 'fa-server',
            "url": '/app/entry/relateList'
          }]
        }]
      }, {
        "id": "171",
        "parentId": "0",
        "name": "网关管理",
        "keyWord": "wggl",
        "icon": 'fa-feed',
        "isExpend": false,
        "children": [{
          "id": "172",
          "parentId": "171",
          "name": "网关更新",
          "keyWord": "wggx",
          "icon": 'fa-columns',
          "url": '/app/gateway/updateList'
        }, {
          "id": "173",
          "parentId": "171",
          "name": "网关任务",
          "keyWord": "wgrw",
          "icon": 'fa-tasks',
          "url": '/app/gateway/gatewayList'
        }]
      }, {
        "id": "181",
        "parentId": "0",
        "name": "官网管理",
        "keyWord": "gwgl",
        "icon": 'fa-map',
        "isExpend": false,
        "children": [{
          "id": "182",
          "parentId": "181",
          "name": "banner管理",
          "keyWord": "banner",
          "icon": 'fa-bandcamp',
          "url": '/app/website/bannerList'
        }, {
          "id": "183",
          "parentId": "181",
          "name": "文章管理",
          "keyWord": "wzgl",
          "icon": 'fa-file-text-o',
          "url": '/app/website/articleList'
        }, {
          "id": "184",
          "parentId": "181",
          "name": "留言管理",
          "keyWord": "wzgl",
          "icon": 'fa-file-text-o',
          "url": '/app/website/messageList'
        }]
      }, {
        "id": "191",
        "parentId": "0",
        "name": "全局节点管理",
        "keyWord": "qjjd",
        "icon": 'fa-support',
        "isExpend": false,
        "children": [{
          "id": "192",
          "parentId": "191",
          "name": "关联管理",
          "keyWord": "glgl",
          "icon": 'fa-bandcamp',
          "url": '/app/point/relateList'
        }]
      }, {
        "id": "201",
        "parentId": "0",
        "name": "产品跳转管理",
        "keyWord": "cptzgl",
        "icon": 'fa-mail-reply-all',
        "isExpend": false,
        "children": [{
          "id": "202",
          "parentId": "201",
          "name": "产品跳转",
          "keyWord": "cptz",
          "icon": 'fa-mail-reply',
          "url": '/app/jump/jumpList'
        }]
      },{
        "id": "301",
        "parentId": "0",
        "name": "手绘本管理",
        "keyWord": "cptzgl",
        "icon": 'fa-book',
        "isExpend": false,
        "children": [{
          "id": "302",
          "parentId": "301",
          "name": "节目单管理",
          "keyWord": "jmdgl",
          "icon": 'fa-star',
          "url": '/app/draw/showList'
        }, {
          "id": "303",
          "parentId": "301",
          "name": "运营元素管理",
          "keyWord": "yyysgl",
          "icon": 'fa-puzzle-piece',
          "url": '/app/draw/operateList'
        }, {
          "id": "304",
          "parentId": "301",
          "name": "页面管理",
          "keyWord": "ymgl",
          "icon": 'fa-file-o',
          "url": '/app/draw/pageList'
        }, {
          "id": "305",
          "parentId": "301",
          "name": "产品页面关联管理",
          "keyWord": "glgl",
          "icon": 'fa-gg',
          "url": '/app/draw/relateList'
        }, {
          "id": "306",
          "parentId": "301",
          "name": "访问入口",
          "keyWord": "fwrk",
          "icon": 'fa-window-maximize',
          "url": '/app/draw/entryList'
        }]
      }, {
        "id": "1",
        "parentId": "0",
        "name": "组件示例",
        "keyWord": "demo",
        "icon": 'fa-wrench',
        "isExpend": false,
        "children": [{
          "id": "2",
          "parentId": "1",
          "name": "消息框",
          "keyWord": "mtk",
          "icon": 'fa-columns',
          "url": '/app/demo/toastDemo'
        }, {
          "id": "3",
          "parentId": "1",
          "name": "模态框",
          "keyWord": "modal",
          "icon": 'fa-columns',
          "url": '/app/demo/modalDemo'
        }, {
          "id": "4",
          "parentId": "1",
          "name": "图表",
          "keyWord": "chart",
          "icon": 'fa-pie-chart',
          "url": '/app/demo/ngxChartsDemo'
        }, {
          "id": "5",
          "parentId": "1",
          "name": "下拉",
          "keyWord": "selectDemo",
          "icon": 'fa-circle',
          "url": '/app/demo/selectDemo'
        }, {
          "id": "6",
          "parentId": "1",
          "name": "层次图",
          "keyWord": "hierarchyView",
          "icon": 'fa-css3',
          "url": '/app/demo/hierarchyViewDemo'
        }, {
          "id": "7",
          "parentId": "1",
          "name": "图片裁剪",
          "keyWord": "imgCropper",
          "icon": 'fa-file-picture-o',
          "url": '/app/demo/imgCropperDemo'
        }, {
          "id": "8",
          "parentId": "1",
          "name": "分页",
          "keyWord": "pagination",
          "icon": 'fa-pagelines',
          "url": '/app/demo/paginationDemo'
        }, {
          "id": "9",
          "parentId": "1",
          "name": "http分页",
          "keyWord": "httpPagination",
          "icon": 'fa-pagelines',
          "url": '/app/demo/httpPaginationDemo'
        }, {
          "id": "10",
          "parentId": "1",
          "name": "开关按钮",
          "keyWord": "switch",
          "icon": 'fa-toggle-on',
          "url": '/app/demo/switchDemo'
        }, {
          "id": "12",
          "parentId": "1",
          "name": "日期选择",
          "keyWord": "datepicker",
          "icon": 'fa-calendar',
          "url": '/app/demo/datepickerDemo'
        }, {
          "id": "13",
          "parentId": "1",
          "name": "树与下拉树",
          "keyWord": "tree",
          "icon": 'fa-tree',
          "url": '/app/demo/treeDemo'
        }, {
          "id": "13",
          "parentId": "1",
          "name": "ztree",
          "keyWord": "ztree",
          "icon": 'fa-tree',
          "url": '/app/demo/ztreeDemo'
        }, {
          "id": "15",
          "parentId": "1",
          "name": "图片转换成base64",
          "keyWord": "imgSelectToBase",
          "icon": 'fa-upload',
          "url": '/app/demo/imgSelectToBaseDemo'
        }, {
          "id": "14",
          "parentId": "1",
          "name": "文件上传",
          "keyWord": "fileUpload",
          "icon": 'fa-upload',
          "url": '/app/demo/fileUploadDemo'
        }, {
          "id": "15",
          "parentId": "1",
          "name": "模拟滚动条",
          "keyWord": "customScrollbarDemo",
          "icon": 'fa-sliders',
          "url": '/app/demo/customScrollbarDemo'
        }, {
          "id": "16",
          "parentId": "1",
          "name": "图片查看器",
          "keyWord": "imageViewerDemo",
          "icon": 'fa-image',
          "url": '/app/demo/imageViewerDemo'
        }, {
          "id": "17",
          "parentId": "1",
          "name": "旋转动画",
          "keyWord": "spinDemo",
          "icon": 'fa-spinner',
          "url": '/app/demo/spinDemo'
        }, {
          "id": "20",
          "parentId": "1",
          "name": "本地存储服务",
          "keyWord": "storageDemo",
          "icon": 'fa-database',
          "url": '/app/demo/storageDemo'
        }, {
          "id": "21",
          "parentId": "1",
          "name": "页面浏览器",
          "keyWord": "pageBrowserDemo",
          "icon": 'fa-circle-thin',
          "url": '/app/demo/pageBrowserDemo'
        }, {
          "id": "22",
          "parentId": "1",
          "name": "富文本编辑器",
          "keyWord": "editorDemo",
          "icon": 'fa-file-o',
          "url": '/app/demo/editorDemo'
        }, {
          "id": "23",
          "parentId": "1",
          "name": "ag-grid",
          "keyWord": "agGridDemo",
          "icon": 'fa-table',
          "url": '/app/demo/agGridDemo'
        }, {
          "id": "24",
          "parentId": "1",
          "name": "简单数据表格",
          "keyWord": "simpleDataTableDemo",
          "icon": 'fa-table',
          "url": '/app/demo/simpleDataTableDemo'
        }, {
          "id": "25",
          "parentId": "1",
          "name": "颜色选择器",
          "keyWord": "colorPickerDemo",
          "icon": 'fa-life-ring',
          "url": '/app/demo/colorPickerDemo'
        }, {
          "id": "26",
          "parentId": "1",
          "name": "步骤条",
          "keyWord": "stepDemoComponent",
          "icon": 'fa-list',
          "url": '/app/demo/stepDemo'
        }, {
          "id": "27",
          "parentId": "1",
          "name": "验证器",
          "keyWord": "validatorDemo",
          "icon": 'fa-life-ring',
          "url": '/app/demo/validatorDemo'
        }, {
          "id": "28",
          "parentId": "1",
          "name": "二维码",
          "keyWord": "qrcodeDemo",
          "icon": 'fa-qrcode',
          "url": '/app/demo/qrcodeDemo'
        }]
      }, {
        "id": "020",
        "parentId": "0",
        "name": "样式示例",
        "keyWord": "yssl",
        "icon": 'fa-cubes',
        "isExpend": false,
        "children": [{
          "id": "021",
          "parentId": "020",
          "name": "ng-bootstrap样式",
          "keyWord": "ngBootstrapDemo",
          "icon": 'fa-cubes',
          "url": '/app/demo/ngBootstrapDemo'
        }, {
          "id": "022",
          "parentId": "020",
          "name": "bootstrap样式",
          "keyWord": "bootstrapDemo",
          "icon": 'fa-cubes',
          "url": '/app/demo/bootstrapDemo'
        }, {
          "id": "023",
          "parentId": "020",
          "name": "时间轴样式",
          "keyWord": "timeline",
          "icon": 'fa-clock-o',
          "url": '/app/demo/timelineDemo'
        }]
      }, {
        "id": "31",
        "parentId": "0",
        "name": "系统管理",
        "keyWord": "xtgl",
        "icon": "fa-cube",
        "children": [{
          "id": "32",
          "parentId": "31",
          "name": "系统监控",
          "keyWord": "txjk",
          "icon": "fa-dashboard",
          "url": "/app/sysMonitor"
        }, {
          "id": "33",
          "parentId": "31",
           "name": "系统日志",
          "keyWord": "txrz",
          "icon": "fa-sticky-note",
          "url": "/app/sysLog"
        }]
      }
    ];
    return menuData;
  }


}
